### ISSUE TITLE
Scrolling the window

### ISSUE THREAD

**Issue by wonnage** [azuqua/react-dnd-scrollzone#5]
Hello,

I would like to use this, but it only supports scrolling a container rather than the whole window. Would this be an easy change to make?

**Comment by nickclaw** [comment]
Hi @wonnage, that probably not something we're going to handle in this project. If you can wrap your DOM in this component (absolutely positioned and taking 100% of the window) it would behave the same way, otherwise the code that actually manages the scrolling should be pretty simple to move into your own code if you want to go down that route.

**Comment by skosch** [comment]
It seems to me that this is an important use case. You could probably just merge this with the `DragLayer` of react-dnd and update the `scrollTop` value of `document.scrollingElement`?
